### ISSUE TITLE
[REGRESSION] Panel always on top of full screen window on primary screen

### ISSUE THREAD

**Issue by adam900710** [linuxmint/muffin#320]
```
 * muffin version: muffin 3.8.1
 * Distribution: Arch
 * Graphic stack: Nvidia 1060, closed source driver
 * 64 bit
 ```

**Issue**
For full screen window, the panel is always on-top of it, which makes full screen terminal unusable.

**Steps to reproduce**
1. Start a VTE based terminal emulator （gnome-terminal, sakura both tried)
2. Get that terminal emulator focused on primary monitor
2. Press F11 to full screen

**Expected behaviour**
When focused, full screen windows should be on top.

**Other information**
It seems that the fix introduced in 3.8.1 to address https://github.com/linuxmint/muffin/issues/316 is not completely correct.

**Comment by mtwebster** [comment]
What terminal are you using, out of curiousity?  Gnome-terminal, mate-terminal, terminator all work properly here.

The fix you mention involves a patch to muffin as well as Cinnamon, are all your packages up to date?

**Comment by adam900710** [comment]
Extra info, the bug only happens on the primary monitor.

Any panels on the secondary monitor doesn't have the problem.

**Comment by adam900710** [comment]
@mtwebster  Sakura, and I also tried gnome-terminal a few minites earlier, the same problem.

And I'm pretty sure I get cinnamon/muffin updated properly, as for previous 3.8, the full screen window is always on top even it's not focused.

So it should be related to the dual-head setup of my environment.

**Comment by itzexor** [comment]
what is your config? mine is 2 1920x1080 side by side with primary on right

HDMI-A-0 connected primary 1920x1080+1920+0 (normal left inverted right x axis y axis) 531mm x 299mm
HDMI-A-1 connected 1920x1080+0+0 (normal left inverted right x axis y axis) 531mm x 299mm

**Comment by adam900710** [comment]
Yep, pretty much the same.
```
HDMI-0 connected primary 1920x1080+0+0 (normal left inverted right x axis y axis) 527mm x 296mm
DP-0 connected 1920x1080+1920+0 (normal left inverted right x axis y axis) 527mm x 296mm
```

And since my sakura hides the toolbar, it's pretty obvious when full screen.

For both terminal full screened: (The left terminal is focused)
![2018-05-10 09-29-46](https://user-images.githubusercontent.com/460269/39847548-d07385fa-5434-11e8-834b-eb46f70d614c.png)

And for both terminal normal:
![2018-05-10 09-29-54](https://user-images.githubusercontent.com/460269/39847571-ed68175c-5434-11e8-953a-360a7f336fb9.png)

**Comment by itzexor** [comment]
is there any extra docks/overlays/non-cinnamon panels or anything like that on the left monitor?

**Comment by adam900710** [comment]
Yep, it turns out that plank (the dock from pantheon DE) is causing the problem.

But still it should be a bug in muffin, or did I miss something?

**Comment by itzexor** [comment]
Thanks, we'll look into it and see what we can do. We had to know where to look first. We hadn't considered the dock window issue until you opened this.

**Comment by adam900710** [comment]
@itzexor  Thanks a lot!

For now I could just workaround the bug by smart hide the panel, so it's far less serious than issue #316.

Or any similar but cinnamon native dock recommendation?

**Comment by itzexor** [comment]
it should be fixed in the next point release. i'm not sure if there's an extension to provide a dock, but it's not supported by the panel code.

**Comment by ultimo44** [comment]
The bug still exists on my machine: 

* Distribution: Linux Mint 19 64 bit
* cinnamon version 3.8.9
* muffin version: muffin 3.8.2
* plank version 0.11.4
